name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test (${{ matrix.buildType }} ${{ matrix.c }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        c: [gcc, clang]
        buildType: [dev, rel]
      fail-fast: false

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup
      uses: PlasmaLang/ci/rotd@master
      with:
        command: setup
        c: ${{ matrix.c }}
        buildType: ${{ matrix.buildType }}
    - name: build
      uses: PlasmaLang/ci/rotd@master
      with:
        command: build
    - name: test
      uses: PlasmaLang/ci/rotd@master
      with:
        command: test
    - name: gctest
      uses: PlasmaLang/ci/rotd@master
      if: matrix.buildType == 'dev'
      with:
        command: gctest

  docs:
    name: Build docs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: docs
      uses: PlasmaLang/ci/docs@master

  lint:
    name: Lint (${{ matrix.buildType }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        buildType: [dev, rel]
      fail-fast: false
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup
      uses: PlasmaLang/ci/rotd@master
      with:
        command: setup
        c: clang
        buildType: ${{ matrix.buildType }}
        lint: lint
    - name: build
      uses: PlasmaLang/ci/rotd@master
      with:
        command: build
    - name: extra
      uses: PlasmaLang/ci/rotd@master
      with:
        command: extra

