name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test (${{ matrix.buildType }} ${{ matrix.c }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        c: [gcc, clang]
        buildType: [dev, rel]
      fail-fast: false

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build
      uses: PlasmaLang/ci/rotd@master
      with:
        makeTarget: progs
        c: ${{ matrix.c }}
        buildType: ${{ matrix.buildType }}
    - name: test
      uses: PlasmaLang/ci/rotd@master
      with:
        makeTarget: test
        c: ${{ matrix.c }} 
        buildType: ${{ matrix.buildType }}
    - name: extra
      uses: PlasmaLang/ci/rotd@master
      with:
        makeTarget: tags
        c: ${{ matrix.c }} 
        buildType: ${{ matrix.buildType }}

  docs:
    name: Build docs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: docs
      uses: PlasmaLang/ci/docs@master

