#
# This is free and unencumbered software released into the public domain.
# See ../LICENSE.unlicense
#

# This workflow controls Plasma's continious integration.  See documentation
# for github workflows:
#
#  * https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-and-managing-workflow-files-and-runs
#  * https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
#
#  And the action we use is here:
#  * https://github.com/PlasmaLang/ci


name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test (${{ matrix.buildType }} ${{ matrix.c }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        c: [gcc, clang]
        buildType: [dev, rel]
      fail-fast: false

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup
      uses: PaulBone/ci/rotd@v1
      with:
        command: setup
        c: ${{ matrix.c }}
        buildType: ${{ matrix.buildType }}
    - name: build
      uses: PaulBone/ci/rotd@v1
      with:
        command: build
    - name: test
      uses: PaulBone/ci/rotd@v1
      with:
        command: test
    - name: gctest
      uses: PaulBone/ci/rotd@v1
      if: matrix.buildType == 'dev'
      with:
        command: gctest

  docs:
    name: Build docs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: docs
      uses: PaulBone/ci/docs@v1

  lint:
    name: Lint (${{ matrix.buildType }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        buildType: [dev, rel]
      fail-fast: false
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup
      uses: PaulBone/ci/rotd@v1
      with:
        command: setup
        c: clang
        buildType: ${{ matrix.buildType }}
        lint: lint
    - name: build
      uses: PaulBone/ci/rotd@v1
      with:
        command: build
    - name: extra
      uses: PaulBone/ci/rotd@v1
      with:
        command: extra

